spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  datasource:

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
#        format_sql: true
#        show_sql: true
      globally_quoted_identifiers: 'true'


#server:

#HS512???? ?? secret key 512bit, ? 64byte??? ?????
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

logging:
  level:
    me.test: DEBUG
